* hibernate,mysql
** BigDecimal的 precision和scale的区别
   precision是总的精度，scale是小数点后几位，比如 BigDecimal（6,2）的
   最大的数就是 9999.99

** @Basic(fetch=FetchType.Lazy)失效问题

   Fetch type is a "hint" to the runtime and the spec doesn't require
   it to be implemented. azy Lob loading would require bytecode
   instrumentation to work properly, so it is not available by default
   in any JPA implementation I'm aware of.

   [http://docs.jboss.org/hibernate/annotations/3.5/reference/en/html_single/]

   To enable property level lazy fetching, your classes have to be
   instrumented: bytecode is added to the original class to enable such
   feature, please refer to the Hibernate reference documentation. If
   your classes are not instrumented, property level lazy loading is
   silently ignored.

   [http://docs.jboss.org/hibernate/core/3.5/reference/en/html/performance.html#performance-fetching-lazyproperties]

   *So the easist way to use lazily quering for One entity in another
   entity is like this*
   
   *@ManyToOne(fetch=FetchType.Lazy)*
   notice that it just works for one-to-one,one-to-many,many-to-one,many-to-many annotation.

   


